name: Deploy Django to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust the version as per your Django project's requirement

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # SSH into EC2 and Deploy
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Navigate to the project directory
          cd /home/ec2-user/priceactionrepository

          # Pull the latest changes
          git pull origin main

          # Set up virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Run Django migrations
          python manage.py migrate

          # Collect static files
          python manage.py collectstatic --noinput

          # Restart the Gunicorn service
          sudo systemctl restart gunicorn

          # Restart Nginx
          sudo systemctl restart nginx
